* Navigating the computer
Using a computer with a screen reader will be hard at first. You
cannot see every item that is available, at once, and there may be
items that a screen reader will skip over or not read correctly due to
accessibility issues in programs and websites. However, the more you
use NVDA, the easier it’ll become, and the more confident you will be
in your ability to navigate the Windows environment.

To navigate the Windows interface, you’ll use a few keys and commands.

- Arrow keys move around text
- The Tab key moves between buttons and other controls
- The F6 key moves between separate parts of a program, like parts of
  a text editor.
- Escape closes menus and dialog boxes

Find out more regarding Windows controls in the /Windows basics with Speech/
course.

* Focus
To deal with keyboard navigation, there is a system of tracking what
the screen reader is currently focusing on. This is called focus, and
you can tell what is in focus by recalling the last item on screen
that NVDA just spoke. 

For example, if NVDA says “taskbar,” that means that the Windows
Taskbar is in focus. If NVDA says:

#+begin_center
Confirmation dialog

Do you want to save this file?

No button
#+end_center

then the “No” button is in focus.

* NVDA navigation aids
There are a few commands to help users figure out where they are in
the Windows environment if you get lost:

- Insert + T :: Read the title bar of the current program
- Insert + Tab :: Read the currently focused control
- Insert + B :: Read the entire window that is currently focused
** Activity
Now, let’s practice dealing with focus. Please complete the following:

- Press the *Windows* key to open the start menu
- Type “notepad” without the quotes
- Press *Enter* to open the program
- Notice what NVDA says when the program opens
- Press *Insert + t* to hear the title of the program. NVDA will say
  “Untitled - Notepad”. This means that the program Notepad is open,
  showing the file called “untitled.”
- Press *Insert + Tab* to hear the currently focused item
- Press *Insert + B* to hear all items in the window
- Press *Alt + F4* to close the program
* Screen reader Jargon
With any technical subject comes jargon, which can be hard to
understand, or even sound silly. These jargon words, however, convey
essential information about the items which the screen reader is
focusing on. Below is a list of terms that you’ll hear when using
NVDA, and their definitions.

- Block quote :: A long quote which takes multiple lines.
- button :: A round item with a label which can be clicked, or
            activated with Space or Enter.
- drop down button :: a button which opens a menu.
- spin button :: a numeric entry field which can be typed into, but
                 also increased or decreased using the arrow keys.
- split button :: a button which can be activated with the Enter key,
                  but has alternative actions which can be accessed
                  using the Space bar.
- toggle button :: a button which toggles a setting on or off.
- Combo box :: a closed box, which can be opened to reveal a list of
               items. Open with Alt + Down arrow, choose an item with
               the arrow keys, and close with Alt + Up arrow.
- Check box :: A box which can be checked or unchecked.
- Dialog :: a window in a program which appears with text in the
            center, and buttons to answer the text with, for example
            yes, no, or OK.
- document :: A place where text is written and edited. Using tab only
              indents text, so use F6 to move to another part of the
              program.
- Edit :: A box for text entry that is one line only.
- Password edit :: an edit field where text typed into the field will
                   not be spoken, only “star”.
- embedded object :: An object on a website that is a web application
     embedded into the site (usually an Adobe flash program, not used
     often).
- graphic :: an image.
- heading :: a headline, which can be in range 1 to 6, 1 being most
             important, 6 being least important.
- landmark :: A navigational device on a website which allows one to
              find important parts of it.
- link :: A hyperlink to a different part of a web page, to a
          different website, or in a program, opens an Internet page
          for showing further information.
- Menu bar :: a bar of menus across the top of a program.
- menu button :: a button which opens a menu.
- radio button :: a button, in a list of buttons, of which only one
                  can be chosen.
- status bar :: a bar at the bottom of a program which gives
                statistics, like a word count or number of errors.
- tab control :: a list of tabs which change the “page” of the program
                 you’re in.
- tree view :: a list with items which can be expanded to show other
               items, or collapsed to hide them.
- window :: a program’s frame on the screen.
- separator :: a horizontal line.
- Menu :: used to select an item from a list.
- submenu :: a menu, accessed with right arrow, inside of a menu.
